server:
  #Dodaję szczegóły dotyczące errorów w odpowiedzi HTTP
  error:
    include-binding-errors: always
    include-message: always
spring:
  profiles:
    active: local
  #Wyłączam standardowy banner Springa
  main:
    banner-mode: OFF
#Tworzę własnego propertiesa
task:
  template:
    allow-multiple-tasks: false
management:
  endpoints:
    web:
      base-path: /status