server:
  #Dodaję szczegóły dotyczące errorów w odpowiedzi HTTP
  error:
    include-binding-errors: always
    include-message: always
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: local
  #Wyłączam standardowy banner Springa
  main:
    banner-mode: OFF
#Tworzę własnego propertiesa
task:
  template:
    allow-multiple-tasks: false
management:
  endpoints:
    web:
      base-path: /status
  metrics:
    enable:
      http: false
keycloak:
  auth-server-url: 'http://localhost:8180'
  realm: 'TodoApp'
  resource: 'todo-spring-app-client'
  public-client: true
  principal-attribute: 'name'
  #Wyłączone na potrzeby testów
  enabled: false