spring:
  #Dodaję dostęp do consoli H2 i zmieniam jej ścieżkę na ./console
  h2:
    console:
      enabled: true
      path: '/console'
  #Zmieniam zachowanie się bazy danych przy uruchamianiu
  jpa:
    hibernate:
      #Create-drop oznacza, że baza tworzy się przy uruchamianiu i resetuje przy kolejnych
      ddl-auto: validate
  #Zmieniam ścieżkę z plikiem bazy danych
  datasource:
    url: 'jdbc:h2:file:.\TasksDB'